### ISSUE TITLE
 exporting a variable named "onCreateWebpackConfig" which isn't an API

### ISSUE THREAD

**Issue by i001962** [djfarly/gatsby-plugin-graphql-preview#11]
I've added this plugin to a gatsby starter and get the following error:

The plugin "gatsby-plugin-graphql-preview@2.1.0" is exporting a variable named "onCreateWebpackConfig" which isn't an API. Perhaps you meant to export "modifyWebpackConfig"?

It's a bit beyond me sorry I'm not much help here but thought I'd report it. 

This repo was working fine, added graphql-preview plugin and now getting error above.

https://github.com/GraphCMS/graphcms-examples/tree/master/current/gatsby-source-plugin-blog

**Comment by djfarly** [comment]
https://twitter.com/djfarly/status/1117486109880139776
The starter did not use gatsby v2 – it's updated now. :)
