### ISSUE TITLE
Compile to ES5

### ISSUE THREAD

**Issue by jariz** [djfarly/gatsby-plugin-graphql-preview#9]
Currently I get errors from IE11 when using this. 😭 
Considering you're already compiling stuff with babel, it's probably a simple matter of only adding a preset.

**Comment by djfarly** [comment]
Oh snap you’re absolutely right, I completely forgot about that.

Do you want to do a PR? I would need to do some research which Babel config would be preferred.

Probably preset-env with this:
https://jamie.build/last-2-versions

**Comment by jariz** [comment]
Yep, I was already working on implementing that but then I started getting 'regeneratorRuntime not defined' errors which probably mean we need to add the babel polyfill or something?
Will look into it tomorrow if I have the time.

**Comment by djfarly** [comment]
Yes, you’re right. babel polyfill is not recommended for libraries though. transform-runtime is the Tool of choice there: https://babeljs.io/docs/en/babel-plugin-transform-runtime
